### ISSUE TITLE
Error calling fix_border_issues()

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [BenWilliams-NOAA/safe#1]
In `main_table` sometimes you use `flextable::fix_border_issues()` and other times just `fix_border_issues()`. The latter throws an error when the flextable library is not loaded. I put a `library(flextable)` call in the main markdown file (near the globals). Is this the best practice? Or you could make it a dependency of the safe package?

**Comment by BenWilliams-NOAA** [comment]
it should be called by the package - i went through yesterday and "should have fixed" those issues. a reinstall of the package should update the `main_table` function. thanks for error checking, i made this "on the fly"!
