### ISSUE TITLE
More control on catch footnote of main table

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [BenWilliams-NOAA/safe#3]
Some stocks assume maxABC for projected years and it would be nice to have this option in the main table. It's hardcoded now [here](https://github.com/BenWilliams-NOAA/safe/blob/main/R/main_table.R#L55), but an easy work around would be if `c2` and `c3` are missing (or null) that the footnote changes to " and maximum permissible ABC for " etc. Alternatively the user could specify a different argument that is just the text of the footnote to give them finer control.

Happy to prototype and do a PR if that's helpful.

**Comment by BenWilliams-NOAA** [comment]
@Cole-Monnahan-NOAA yeah a couple ways to address this. 1 is to add a switch in the function you link to, 2. (and what I do) is that I pull the values from the proj .dat file in the safe as "global" variables https://github.com/afsc-assessments/goa_nork/blob/939f472a502c3f3625d293b097d7eb5f653ae400/2023/safe/safe.Rmd#L73

Does one of those approaches seem more better than the other to you?

**Comment by Cole-Monnahan-NOAA** [comment]
@BenWilliams-NOAA Yeah good point I think that's a better approach and I adopted it this year. Closing.
