### ISSUE TITLE
Request to specify manual catch statement in main_table

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [BenWilliams-NOAA/safe#5]
On this line [here](https://github.com/BenWilliams-NOAA/safe/blob/main/R/main_table.R#L56) there is some hard-coded verbiage for the catch statements. This does not apply to all stocks, e.g., if the maxABC is assumed. Could we add an optional argument which would allow the user to bypass this. Something like

`main_table(..., catch_text=paste0('based on catches of',c1, 'etc.'))`

**Comment by BenWilliams-NOAA** [comment]
just added a fully manual footnote, though it will still need a footnote of some sort cause the years will have an asterisk on them
